import { Icon } from 'antd';
import version from '../../config/iconFontConfig';

const ZetIcon = Icon.createFromIconfontCN({
  // scriptUrl: '//at.alicdn.com/t/font_810702_0wr5qh39yre.js', // generated by iconfont.cn
  // scriptUrl: '//at.alicdn.com/t/font_810702_gtugwqme7je.js',
  // scriptUrl: '/icon/font_810702_roevf7cc95p/iconfont.js',
  scriptUrl: `/icon/${version}/iconfont.js`,
});

export default ZetIcon;
